// cvThiagoQuaglia/src/pages/Home/Home.tsx
import Contact from "./components/Contact/Contact";
import Navbar from "../../components/Navbar";
import Personal from "./components/Personal/Personal"
import Projects from "./components/Projects/Projects";
import Skills from "./components/Skills/Skills";
import "./Home.css";

export default function Home(): JSX.Element {
  return (
    <>
      <Navbar inProjectPage={false}/>
      <div className="start circle-in-animation">
        <div transition-style="">
          <div className="whoami">
            <h1 className="name">Thiago Quaglia</h1>
            <h2 className="profession">Junior Software Developer</h2>
          </div>
        </div>
      </div>

      <div className="sections">
        <div className="about" id="about">
          <div>
            <p>
              Mi nombre es Thiago Quaglia. Desde pequeño que soy muy aficionado
              a la tecnología, lo que me ha permitido inclinarme por la
              programación a la hora de comenzar con los estudios.
            </p>
            <p>
              Actualmente, finalizando la carrera de "Analista Universitario en
              Sistemas".
            </p>
            <p>
              Estoy en busca de mi primer experiencia laboral en el ámbito de
              desarrollo de software, que me permita incorporar conocimientos
              nuevos y profundizar los adquiridos.
            </p>
          </div>
        </div>

        <Personal />
        <Skills />
        <Projects />
        <Contact/>
      </div>
    </>
  );
}

// src/app/home/home.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent implements OnInit {
  copied:boolean;

  constructor() {
    this.copied = false;
  }

  ngOnInit(): void {}
}

<div class="container">
  <div class="navbar">
    <a href="#about">about</a>
    <a href="#personal">personal info</a>
    <a href="#skills">skills</a>
    <a routerLink="/proyects">proyectos</a>
  </div>

  <div class="start">
    <div class="whoami">
      <h1 class="name">Thiago Quaglia</h1>
      <h2 class="profession">Junior Software Developer</h2>
    </div>
  </div>

  <div class="about" id="about">
    <p>
      Me llamo Thiago Quaglia. Desde pequeño que soy muy aficionado a la
      tecnología, lo que me ha permitido inclinarme por la programación a la
      hora de comenzar con los estudios.
    </p>
    <p>
      Actualmente, finalizando la carrera de "Analista Universitario en
      Sistemas".
    </p>
    <p>
      Estoy en busca de mi primer experiencia laboral en el ámbito de desarrollo
      de software, que me permita incorporar conocimientos nuevos y ampliar y
      profundizar los adquiridos.
    </p>
  </div>

  <div class="section" id="personal">
    <div class="row">
      <div class="col-md-6 col-sm-12">
        <h2>Formación académica</h2>
        <ul>
          <li>
            <h3>Secundario</h3>
            <div>
              <b>“Instituto Santa María Goretti E.E.S.O.P.I. 8097”</b> , Arroyo
              Seco, Santa Fe, Argentina.
              <br />
              <b>2015</b> - <b>2019</b>.
              <br />
              <b>Bachiller en Ciencias Sociales.</b>
            </div>
          </li>
          <li>
            <h3>Terciario</h3>
            <div>
              <b>"Instituto Politécnico Superior – UNR”</b>, Rosario, Santa Fe,
              Argentina.
              <br />
              <b>2020</b> - <b>2023</b>.
              <br />
              Me queda una materia para recibirme.
              <br />
              <b>Analista Universitario en Sistemas.</b>
            </div>
          </li>
        </ul>
      </div>
      <div class="col-md-6 col-sm-12">
        <h2>Idiomas</h2>
        <div>
          <ul>
            <li>
              <h3>Castellano</h3>
              <div>
                <b>Nativo.</b>
              </div>
            </li>
            <li>
              <h3>Inglés</h3>
              <div>
                <b>Alto.</b>
              </div>
            </li>
          </ul>
        </div>
      </div>
      <div class="col-md-6 col-sm-12">
        <h2>Disponibilidad</h2>
        <ul>
          <li>
            <h3>Full-Time.</h3>
          </li>
        </ul>
      </div>
      <div class="col-md-6 col-sm-12">
        <h2>Intereses</h2>
        <ul>
          <li>
            <h3>Desarrollo de apps en general.</h3>
          </li>
          <li>
            <h3>A nivel desarrollo web</h3>
            <div>
              <b>Backend.</b>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </div>

  <div class="section" id="skills">
    <h1 class="skills_header">Habilidades</h1>
    <div class="row">
      <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
        <circle-progress
          [percent]="80"
          [radius]="100"
          [outerStrokeWidth]="16"
          [innerStrokeWidth]="8"
          [outerStrokeColor]="'#000000'"
          [innerStrokeColor]="'#ffff00'"
          [animation]="true"
          [animationDuration]="300"
          [title]="'JAVA'"
          [showUnits]="false"
          [showSubtitle]="false">
        </circle-progress>
      </div>
      <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
        <circle-progress
          [percent]="80"
          [radius]="100"
          [outerStrokeWidth]="16"
          [innerStrokeWidth]="8"
          [outerStrokeColor]="'#000000'"
          [innerStrokeColor]="'#ffff00'"
          [animation]="true"
          [animationDuration]="300"
          [title]="'C'"
          [showUnits]="false"
          [showSubtitle]="false">
        </circle-progress>
      </div>
      <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
        <circle-progress
          [percent]="75"
          [radius]="100"
          [outerStrokeWidth]="16"
          [innerStrokeWidth]="8"
          [outerStrokeColor]="'#000000'"
          [innerStrokeColor]="'#ffff00'"
          [animation]="true"
          [animationDuration]="300"
          [title]="'C++'"
          [showUnits]="false"
          [showSubtitle]="false">
        </circle-progress>
      </div>
      <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
        <circle-progress
          [percent]="75"
          [radius]="100"
          [outerStrokeWidth]="16"
          [innerStrokeWidth]="8"
          [outerStrokeColor]="'#000000'"
          [innerStrokeColor]="'#ffff00'"
          [animation]="true"
          [animationDuration]="300"
          [title]="'C#'"
          [showUnits]="false"
          [showSubtitle]="false">
        </circle-progress>
      </div>
      <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
        <circle-progress
          [percent]="55"
          [radius]="100"
          [outerStrokeWidth]="16"
          [innerStrokeWidth]="8"
          [outerStrokeColor]="'#000000'"
          [innerStrokeColor]="'#ffff00'"
          [animation]="true"
          [animationDuration]="300"
          [title]="'.NET'"
          [showUnits]="false"
          [showSubtitle]="false">
        </circle-progress>
      </div>
      <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
        <circle-progress
          [percent]="55"
          [radius]="100"
          [outerStrokeWidth]="16"
          [innerStrokeWidth]="8"
          [outerStrokeColor]="'#000000'"
          [innerStrokeColor]="'#ffff00'"
          [animation]="true"
          [animationDuration]="300"
          [title]="'ASP.NET'"
          [showUnits]="false"
          [showSubtitle]="false">
        </circle-progress>
      </div>
      <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
        <circle-progress
          [percent]="63"
          [radius]="100"
          [outerStrokeWidth]="16"
          [innerStrokeWidth]="8"
          [outerStrokeColor]="'#000000'"
          [innerStrokeColor]="'#ffff00'"
          [animation]="true"
          [animationDuration]="300"
          [title]="'SPRING'"
          [showUnits]="false"
          [showSubtitle]="false">
        </circle-progress>
      </div>
      <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
        <circle-progress
          [percent]="70"
          [radius]="100"
          [outerStrokeWidth]="16"
          [innerStrokeWidth]="8"
          [outerStrokeColor]="'#000000'"
          [innerStrokeColor]="'#ffff00'"
          [animation]="true"
          [animationDuration]="300"
          [title]="'ANGULAR'"
          [showUnits]="false"
          [showSubtitle]="false">
        </circle-progress>
      </div>
      <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
        <circle-progress
          [percent]="70"
          [radius]="100"
          [outerStrokeWidth]="16"
          [innerStrokeWidth]="8"
          [outerStrokeColor]="'#000000'"
          [innerStrokeColor]="'#ffff00'"
          [animation]="true"
          [animationDuration]="300"
          [title]="'MySQL'"
          [showUnits]="false"
          [showSubtitle]="false">
        </circle-progress>
      </div>
      <div class="col-lg-3 col-md-4 col-sm-6 col-xs-12">
        <circle-progress
          [percent]="75"
          [radius]="100"
          [outerStrokeWidth]="16"
          [innerStrokeWidth]="8"
          [outerStrokeColor]="'#000000'"
          [innerStrokeColor]="'#ffff00'"
          [animation]="true"
          [animationDuration]="300"
          [title]="'SQL SERVER'"
          [showUnits]="false"
          [showSubtitle]="false">
        </circle-progress>
      </div>
    </div>
  </div>

  <div class="section contact">
    <ul class="wrapper">
     <a href="mailto:thiagoqua16@gmail.com">
        <li class="icon mail" style="text-align: center;">
          <span id="mail" class="tooltip">Email</span>
          <span><i class="fab fa-facebook-f"></i></span>
        </li>
      </a>
      <a target="_blank" href="https://www.linkedin.com/in/thiagoquaglia">
        <li class="icon linkedin">
          <div class="tooltip" style="font-weight: 600;">Linkedin</div>
          <span><i class="fab fa-twitter"></i></span>
        </li>
      </a>
      <a target="_blank" href="https://github.com/thiagoqua">
        <li class="icon github">
          <span class="tooltip">GitHub</span>
          <span><i class="fab fa-instagram"></i></span>
        </li>
      </a>
    </ul>
  </div>
</div>
